import collections
import json
import os

class BlackBoxRingBuffer:
    def __init__(self, max_frames=1250):  # 1250 frames stores ~5 seconds at 250Hz
        self.buffer = collections.deque(maxlen=max_frames)
        
    def append_frame(self, telemetry_frame):
        """Pushes every sequential frame generated by your HAL into memory."""
        self.buffer.append(telemetry_frame)
        
        # Check if this state represents a fatal system failure crash
        if telemetry_frame.get("health_status") == "EMERGENCY_STOP":
            self.flush_to_disk()

    def flush_to_disk(self):
        """Dumps the pre-crash timeline history securely to disk for post-mortems."""
        os.makedirs("blackbox_logs", exist_ok=True)
        dump_path = "blackbox_logs/crash_dump_telemetry.json"
        
        # Convert queue collection cleanly to serializable structure
        historical_snapshot = list(self.buffer)
        
        with open(dump_path, "w") as f:
            json.dump(historical_snapshot, f, indent=2)
        print(f"\n[!] CRITICAL: Black Box Buffer Locked. {len(historical_snapshot)} frames dumped to {dump_path}")